config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get 'analytics', to: 'pages#analytics', as: 'analytics'
  get 'cards', to: 'pages#cards', as: 'cards'

  # Defines the root path route ("/")
  # root "posts#index"

  #routes for budgets
  resources :categories do
    resources :budgets, only: [:edit, :new, :create, :update]
    # Nested routes for budgets under categories
  end

    #Routes for managing transactions
  resources :transactions, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :max_limit, presence:true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :transactions
  has_many :budgets
  has_many :categories, through: :budgets
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :amount, presence: true, numericality: true
  validates :date, presence: true
  validates :retailer, presence: true
  validates :bank, presence: true
  validates :category_id, presence: true
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :category

  include PgSearch::Model
  pg_search_scope :search_by_category_id,
    against: [ :category_id],
    using: {
      tsearch: { prefix: false } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :budgets
  has_many :transactions
  has_many :categories, through: :budgets
  has_one_attached :photo, dependent: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_category, only: [:new, :create, :edit, :update, :destroy]

    #new form for new budget
  def new
    @budget = Budget.new
  end

  #create new budget
  def create
    @budget = @category.budgets.new(budget_params)
    @budget.user = current_user # Assign the current user to the budget
    if @budget.save
    #change the root_path
      redirect_to transactions_path, notice: 'Budget created successfully.'
    else
      render :new
    end
  end

  #edit budget
  def edit
    @budget = @category.budgets.first
  end

  #update budget
  def update
    @budget = current_user.budgets.find(params[:id])
    if @budget.update(budget_params)
      #change the root path
      redirect_to transactions_path, notice: 'Budget updated successfully.'
    else
      render :edit
    end
  end

  # delete budget
  def destroy
    @budget = current_user.budgets.find(params[:id])
    @budget.destroy
    #change the root path
    redirect_to transactions_path, notice: 'Budget deleted successfully.'
  end

  private
  #set category based on category name
  def set_category
    @category = Category.find(params[:category_id])
    @category_name = @category.name
  end

  #strong params needed to create budget
  def budget_params
    params.require(:budget).permit(:category_id, :max_limit)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def cards
  end

  def analytics
    user_transactions = current_user.transactions
    @transactions = []
    if params[:period]
      @month = params[:period].to_i
      @range =  @month.month.ago..Time.now
      @days = 30 * params[:period].to_i
      transactions = search_by_days(user_transactions, @days)
    else
      @range = 1.month.ago..Time.now
      @days = 30
      transactions = search_by_days(user_transactions, @days)
    end
    @total = transactions.inject(0) { |sum, transaction| sum + transaction.amount }
    @total = (@total * 100).floor / 100.0
    transactions.each do |transa|
      @transactions << transaction_info(transa)
    end
  end

  private

  def search_by_days(transactions, days)
    require 'date'

    # Get the current date
    current_date = Date.today
    # select the transactions from the past 30days
    selected_transactions = transactions.select do |transa|
      current_date - transa.date < days.to_i
    end
    sorted_transactions = selected_transactions.sort_by { |transa| transa.date }
    return sorted_transactions
  end

  def transaction_info(transaction)
    details = {
      amount: transaction.amount,
      date: transaction.date.strftime('%a, %d %b %Y'),
      retailer: transaction.retailer,
      bank: transaction.bank,
      category: transaction.category.name
    }
    return details
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    # raise
    # give me all the transactions for the current user
    user_transactions = current_user.transactions
    # array to store each transacion's information
    @transactions = []
    @overall_spend = 0

    if params[:category].present?
      input = params[:category]
      user_transactions = search_by_category(user_transactions, input)
      @monthly_spend = Category.find_by(name: input).monthly_spend
      @totat_spend = Category.find_by(name: input).total_spend
      @page_category = input
      category = Category.find_by(name: @page_category)
      budget = category.budgets
      if budget.any?
        @budget = budget.first
        @budget_limit = budget.first.max_limit
      else
        @budget = false
      end
      @monthly_spend = category.monthly_spend
      @category = category
      # raise
    end


    if params[:period].present?
      user_transactions = search_by_days(user_transactions, params[:period])
    end

    if params[:bank].present?
      user_transactions = search_by_bank(user_transactions, params[:bank])
    end

    if params[:amount].present?
      user_transactions = search_by_amount(user_transactions, params[:amount])
    end
    sorted_transactions = user_transactions.sort_by { |transa| transa.date }
    sorted_transactions.each do |transa|
      # for each transaction pass it to the function to get the its information ie.its amount, date ...
      transaction = transaction_info(transa)
      # store the information in the @transactions array
      @transactions << transaction
      @overall_spend += transa.amount
    end

    # raise
  end

  private


  def search_by_days(transactions, days)
    require 'date'

    # Get the current date
    current_date = Date.today
    # select the transactions from the past 30days
    selected_transactions = transactions.select do |transa|
      current_date - transa.date < days.to_i
    end
    return selected_transactions
  end

  def search_by_category(transactions, category)
    # select the transactions that have this category
    selected_transactions = transactions.select do |transa|
      transa.category.name == category
    end
    # raise
    return selected_transactions
  end

  def search_by_bank(transactions ,bank)
    selected_transactions = transactions.select do |transa|
      transa.bank == bank
    end
    # raise
    return selected_transactions
  end

  def search_by_amount(transactions ,amount)
    selected_transactions = transactions.select do |transa|
      transa.amount > amount
    end
    # raise
    return selected_transactions
  end

  def get_budget(transaction)
    #get the category of the budget
    category = transaction.category
    # find the budget with this category_id
    budget = Budget.find_by(category_id: category.id)
    return budget
  end

  def transaction_info(transaction)
    details = {
      amount: transaction.amount,
      date: transaction.date.strftime('%a, %d %b %Y'),
      retailer: transaction.retailer,
      bank: transaction.bank,
      category: transaction.category.name
    }
    return details
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/budgets/_category.html.erb
<h1> <%@category.name.capitalize%> </h1>
<div class="budget-content">
  <div class="budget-hero">
    <%if @category.name == 'restaurant'%>
    <div class="category-hero">
      <h1 class="category-title"><%=@category.name%></h1>
      <box-icon color='#ff8a5c' name='restaurant' animation='tada' ></box-icon>
    </div>
    <%elsif  @category.name == 'supermarket' %>
      <h1 class="category-title"><%=@category.name%></h1>
      <box-icon color='#ff8a5c' animation="tada" name='cart-alt'type="solid"></box-icon>
    <%elsif @category.name == 'subscriptions' %>
      <h1 class="category-title"><%=@category.name%></h1>
      <box-icon color='#ff8a5c' animation="tada" name='dice-5'type="solid"></box-icon>
    <%elsif @category.name == 'utilities' %>
      <h1 class="category-title"><%=@category.name%></h1>
      <box-icon color='#ff8a5c' animation="tada" name='wrench'type="solid"></box-icon>
    <% elsif @category.name == 'home' %>
      <h1 class="category-title"><%=@category.name%></h1>
      <box-icon color='#ff8a5c' animation="tada" name='home-heart'type="solid"></box-icon>
    <% end%>
  </div>
  <div class="budget-form">
    <%= render 'form' %>
  </div>
</div>

app/views/budgets/_form.html.erb
<%= simple_form_for [@category, @budget], html: {class: 'budget-form'} do |f|%>
    <div class="field">
      <%= f.input :max_limit %>
    </div>
    <%= f.submit 'Set limit', class: 'limit-btn' %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<%= render 'category' %>

app/views/budgets/new.html.erb
<%= render 'category' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puurse</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "puurse_logo_480.png" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>

  </head>

  <body>
    <%= render "shared/flashes" %>

    <div class="d-flex">
      <% if user_signed_in? %>
        <%= render "shared/navbar" %>
      <% end %>


      <div class="yield flex-grow-1">
        <%= yield %>
      </div>
    </div>


  </body>
</html>

app/views/pages/analytics.html.erb
<div class="standard-structure">
<div class="analytics-page">
  <% if user_signed_in? %>
    <div class="analytics-form">
      <%= form_with url: analytics_path, method: :get, class: "a-form" do %>
        <div class="a-input">
          <%= select_tag :period, options_for_select([["Select Period ▽"],["1 month", 1],["3 months", 3],["6 months", 6],["9 months", 9],["1 year", 12]]), class: "form-control form-select-period", onchange: "this.form.submit()" %>
        </div>
      <% end %>
      <h2>Total Spend: <strong><%=number_to_currency(@total,unit:"£")%> </strong></h2>
    </div>
    <div class="analytics-container">

      <div class="area-chart">
        <h3>Your Spending Timeline </h3>
        <%= area_chart Transaction.group_by_day(:date, range: @range).sum(:amount), height: "550px", class:"line-chart", colors: ["#404040", "#FF8A5C"], xmax: "2024-05-15", max: 250, xtitle: "Date" %>
            <div class="pie-chart">
        <h4>Monthly Spend by Category </h4>
        <%= pie_chart Category.group(:name).sum(:monthly_spend), height: "500px", width: "600px",  legend: "right", colors: ["#FF8A5C", "#404040", "#949494", "#F6F4F4", "#49BEB7"] %>
      </div>
        <%= render 'transactions/transactions' %>
      </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/pages/cards.html.erb
<div class="content-box" data-controller="categories" >
    <div class="bank-card">
      <%= link_to transactions_url, class: "text-decoration-none" do%>
        <%# <%= image_tag("blank_bank_card.png", alt: "Image Description") %>
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <%= image_tag("front-card2.png", alt: "Image Description") %>
    </div>
    <div class="flip-card-back">
      <%= image_tag("name_bank_card.png", alt: "Image Description") %>
    </div>
  </div>
</div>
<% end %>
    </div>

</div>

app/views/pages/home.html.erb
<div class="page-content">
  <div class="home-page">
    <%= image_tag("puurse_logo.png", alt: "Image Description", class: "logo-home") %>
    <h2>Empower Your Finances, Shape Your Future with Puurse</h2>
    <div class="buttons-and-image position-relative">
      <div class="buttons d-flex flex-column flex-shrink-0 position-absolute">
        <button class = "h3-button"> <%= link_to 'Manage your Transactions', transactions_path, class: "text-decoration-none" %> </button>
        <button class = "h3-button"> <%= link_to 'Track your Analytics', analytics_path %> </button>
        <button class = "h3-button"> <%= link_to 'View your Cards', transactions_path %> </button>
      </div>
      <img src="https://cdn.dribbble.com/userupload/9471508/file/original-734be9806ad041ddbb1c29536998a043.png?resize=1504x1128" alt="home-page">
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav">
  <div class="logo">
    <%= link_to root_path, class: "home-link" do %>
      <%= image_tag("puurse_logo.png", alt: "Image Description") %>
    <% end %>
  </div>

  <div class="main">
    Main

    <%= link_to root_path, class: "nav-button" do %>
      <box-icon name='home' type='solid' color='#404040' ></box-icon>
      <p>Home</p>
    <% end %>

    <%= link_to transactions_path, class: "nav-button #{'nav-active' if params[:controller] == "transactions" && params[:action] == "index"}" do %>
      <%# <box-icon name='transfer-alt' type='solid' color='#404040'></box-icon> %>
      <i class="fa-solid fa-money-bill-transfer"></i>
      <p>Transactions</p>
    <% end %>

    <%= link_to analytics_path , class: "nav-button" do %>
      <box-icon name='pie-chart-alt-2' type='solid' color='#404040'></box-icon>
      <p>Analytics</p>
    <% end %>

    <%= link_to cards_path , class: "nav-button" do %>
      <box-icon name='credit-card' type='solid' color='#404040' ></box-icon>
      <p>Cards</p>
    <% end %>


  </div>

  <div class="other">
    Other
    <%= link_to "Settings", class: "nav-button" do %>
      <box-icon type='solid' name='help-circle' color='#404040'></box-icon>
      <p>Get Help</p>
    <% end %>


    <%= link_to "Settings", class: "nav-button" do %>
      <box-icon name='cog' type='solid' color='#404040'></box-icon>
      <p>Settings</p>
    <% end %>
    <br>
    <hr>
    <div class="profile">
      <%if user_signed_in?%>
        <%= link_to edit_user_registration_path do %>
          <span><%=current_user.first_name %></span>
          <%if current_user.photo.key %>
            <%= cl_image_tag current_user.profile_photo.key, height: 80, width: 80, crop: :fill, style: 'border-radius: 50%; margin-right:1rem; padding: 0;' %>
          <% else%>
            <%= image_tag "profile-photo.jpg" %>
          <% end %>
        <%end%>
      <%end%>
    </div>
  </div>
</div>
<div class="nav-spacer"> </div>

app/views/transactions/_transactions.html.erb
<div class="transactions" data-categories-target="list">
  <% @transactions.each do |transaction| %>
  <div class="t-card">
    <div class="left">
      <div class="col1">
        <% if transaction[:category]  == "restaurant" %>
          <box-icon name='restaurant' color='#ff8a5c' class="t-icon" ></box-icon>
        <% elsif transaction[:category]  == "supermarket"  %>
          <box-icon name='cart' type='solid' color='#ff8a5c' class="t-icon"></box-icon>
        <% elsif transaction[:category]  == "subscriptions"  %>
           <box-icon name='calendar-check' type='solid' color='#ff8a5c' class="t-icon" ></box-icon>
        <% elsif transaction[:category]  == "home"  %>
          <box-icon name='wrench' type='solid' color='#ff8a5c' class="t-icon"></box-icon>
        <% elsif transaction[:category]  == "utilities" %>
          <box-icon name='cart' type='solid' color='#ff8a5c' class="t-icon"></box-icon>
        <% end %>


        <%# <box-icon name='basket' color='#ff8a5c' class="t-icon"></box-icon> %>
      </div>
      <div class="col2">
        <span><%= transaction[:retailer].capitalize %></span>
        <p><%= transaction[:date] %></p>
      </div>
    </div>


      <div class="col3">
        <%# <box-icon name='calendar' type='solid' color='#ff8a5c' ></box-icon> %>
        <p>£<%= transaction[:amount] %></p>
      </div>

  </div>
  <% end %>
</div>

app/views/transactions/index.html.erb
<div class="page-content">

  <div class="content-box" data-controller="categories" >
    <div class="bank-card">
      <%= link_to transactions_url, class: "text-decoration-none" do%>
        <%# <%= image_tag("blank_bank_card.png", alt: "Image Description") %>
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <%= image_tag("front-card2.png", alt: "Image Description") %>
    </div>
    <div class="flip-card-back">
      <%= image_tag("name_bank_card.png", alt: "Image Description") %>
    </div>
  </div>
</div>

    </div>
    <%if @page_category%>
      <%else%>
        <h3>All Transactions</h3>
      <%end %>

    <div class="category-icons">
    <% if @page_category %>
      <%if params[:category] == 'Restaurant'%>
        <%# <box-icon color='#ff8a5c' name='restaurant' animation='rotate' ></box-icon> %>
        <h4 class="category-title"><%=@page_category%></h4>
      <% elsif params[:category] == 'supermarket' %>
        <%# <box-icon color='#ff8a5c' animation="rotate" name='cart-alt'type="solid"></box-icon> %>
        <h4 class="category-title"><%=@page_category%></h4>


      <% elsif params[:category] == 'Subscriptions' %>
        <%# <box-icon color='#ff8a5c' animation="tada" name='dice-5'type="solid"></box-icon> %>
        <h4 class="category-title"><%=@page_category%></h4>


      <% elsif params[:category] == 'Utilities' %>
        <%# <box-icon color='#ff8a5c' animation="tada" name='wrench'type="solid"></box-icon> %>
        <h4 class="category-title"><%=@page_category%></h4>

      <% elsif params[:category] == 'Home' %>
        <%# <box-icon color='#ff8a5c' animation="tada" name='home-heart'type="solid"></box-icon> %>
        <h4 class="category-title"><%=@page_category%></h4>

      <% end%>
    <% else %>

    <% end %>
    </div>


    <%end%>


    <div class="t-categories">
      <%= form_with url: transactions_url, method: :get, class: "a-form col-1 ", html: {class: 'search-form'}  do %>
      <span>Category</span>
      <div class="input-box">
        <% categories = [['utilities'], ['supermarket'], ['restaurant'], ['home'], ['subscriptions']] %>
        <% categories.each do |category| %>
          <%= radio_button_tag 'category', category[0], false, class: 'category-input'%>
          <%# <%= raise %>
          <%= label_tag "category_#{category[0]}", category[0], class: "category-label #{'checkbox-active' if params[:category] == category[0]}" %><br>
        <% end %>
      </div>
      <div class="select-container">
        <div class="select-box">
          <span>Time Period</span>
          <%= select_tag 'period', options_for_select([[],['30 Days'], ['60 Days'], ['90 Days'], ['120 Days']]), class: 'category-select' %>
        </div>
        <div class="select-box">
          <span>Account</span>
          <%= select_tag 'Account', options_for_select([[],['Natwest'], ['Barclays'], ['Revolut'], ['HSBC']]), class: 'category-select' %>
        </div>
        <div>
          <%= submit_tag 'Apply', class:'form-submit'%>
        </div>
      </div>
      <% end %>
    </div>
    <div class="budget-info">


      <div class="total-spend col-4 text-center">
        <%if @page_category%>
          <p>Total spend <span class="amount"><%=number_to_currency((@overall_spend * 100).floor/100.0,unit:"£")%><%="/£#{@budget_limit}" if @budget_limit%></span></p>
        <%else%>
          <p>Total spend: <span class="amount"><%=  number_to_currency((@overall_spend * 100).floor/100.0,unit:"£") %></span></p>
        <% end%>
      </div>
      <i class="transactions-size col-4 text-center" ><%=@transactions.size%> transactions</i>

      <div class="limit col-4 text-center">

        <% if @page_category%>
          <% if @budget%>

            <%= link_to 'Edit limit', edit_category_budget_path(@category, @budget), class: 'limit-btn' %>
          <%else%>
            <%= link_to '+ Add limit', new_category_budget_path(@category), class: 'limit-btn' %>
          <%end%>
        <% end %>
      </div>

    </div>
    <%= render 'transactions' %>
  </div>
</div>